services:
  search:
    image: getmeili/meilisearch:latest
    volumes:
      - meilei_data:/meili_data
    ports:
      - 7700:7700
    env_file:
      - .env
  frontend:
    build: .
    ports:
      - 8080:80

volumes:
  meilei_data: